Vagrant.configure('2') do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_version = "20191107.0.0"

  config.vm.define "ekaraogltestS" do |machine|
    machine.vm.network "private_network", ip: '192.168.56.110'
    machine.vm.hostname = "ekaraogltestS"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "ekaraogltestS"
      vb.cpus = '1'
      vb.memory = '512'
    end
  end
  config.vm.define "ekaraogltestSW" do |machine|
    machine.vm.network "private_network", ip: '192.168.56.111'
    machine.vm.hostname = "ekaraogltestSW"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "ekaraogltestSW"
      vb.cpus = '1'
      vb.memory = '512'
    end
  end
end